"""Add AspectCategory model and link to AspectSentiment

Revision ID: 5273cafd9a74
Revises: 
Create Date: 2025-09-23 18:09:38.270527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5273cafd9a74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('admin_username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               type_=sa.String(length=80),
               existing_nullable=False)

    with op.batch_alter_table('aspect_sentiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_extracted_aspect', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('aspect_category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('keyword_found',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('sentence',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('start_char',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('end_char',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_foreign_key(None, 'aspect_category', ['aspect_category_id'], ['id'])
        batch_op.drop_column('aspect')

    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=False)
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('aspect_sentiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aspect', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('end_char',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('start_char',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sentence',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=False)
        batch_op.alter_column('keyword_found',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               existing_nullable=False)
        batch_op.drop_column('aspect_category_id')
        batch_op.drop_column('raw_extracted_aspect')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('admin_username',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
